#pragma once

namespace rage
{
    enum class eTimecycle 
    {
        TIMECYCLE_EXTRA_SUNNY,
        TIMECYCLE_SUNNY,
        TIMECYCLE_EXTRASUNNY_SMOG,
        TIMECYCLE_SUNNY_WINDY,
        TIMECYCLE_CLOUDY,
        TIMECYCLE_RAINY,
        TIMECYCLE_DRIZZLE,
        TIMECYCLE_FOGGY,
        TIMECYCLE_LIGHTNING,
        TIMECYCLE_EXTRA_SUNNY_NIGHT,
        TIMECYCLE_SUNNY_NIGHT,
        TIMECYCLE_EXTRASUNNY_SMOG_NIGHT,
        TIMECYCLE_SUNNY_WINDY_NIGHT,
        TIMECYCLE_CLOUDY_NIGHT,
        TIMECYCLE_RAINY_NIGHT,
        TIMECYCLE_DRIZZLE_NIGHT,
        TIMECYCLE_FOGGY_NIGHT,
        TIMECYCLE_LIGHTNING_NIGHT
    };
}


