#pragma once

namespace rage
{
    enum class VehicleType
    {
        VEHICLE_TYPE_INVALID = -1,
        VEHICLE_TYPE_CAR,
        VEHICLE_TYPE_MOTORCYCLE,
        VEHICLE_TYPE_BOAT,
        VEHICLE_TYPE_HELICOPTER,
        VEHICLE_TYPE_AIRPLANE,
        VEHICLE_TYPE_BICYCLE,
        VEHICLE_TYPE_TRAIN,
        VEHICLE_TYPE_EMERGENCY,
        VEHICLE_TYPE_INDUSTRIAL,
        VEHICLE_TYPE_PUBLIC_SERVICE,
        VEHICLE_TYPE_TAXI,
        VEHICLE_TYPE_COMMERCIAL,
        VEHICLE_TYPE_SPECIAL,
        VEHICLE_TYPE_NONE
    };
}