#pragma once

enum class eVehicleColor
{
    VEHICLE_COLOR_UNKNOWN = 0,
    VEHICLE_COLOR_BLACK = 1,
    VEHICLE_COLOR_GRAPHITE = 2,
    VEHICLE_COLOR_BLACKSTEEL = 3,
    VEHICLE_COLOR_DARKSTEEL = 4,
    VEHICLE_COLOR_SILVER = 5,
    VEHICLE_COLOR_BLUESTEEL = 6,
    VEHICLE_COLOR_AQUA = 7,
    VEHICLE_COLOR_PALEBLUE = 8,
    VEHICLE_COLOR_BLUE = 9,
    VEHICLE_COLOR_SEAFOAMBLUE = 10,
    VEHICLE_COLOR_LIGHTBLUE = 11,
    VEHICLE_COLOR_MIDNIGHTBLUE = 12,
    VEHICLE_COLOR_NAVYBLUE = 13,
    VEHICLE_COLOR_ROYALBLUE = 14,
    VEHICLE_COLOR_LIGHTBLUE2 = 15,
    // add more colors here

    // Special colors
    VEHICLE_COLOR_METALLICBLACK = 98,
    VEHICLE_COLOR_METALLICGRAPHITE = 99,
    VEHICLE_COLOR_METALLICBLACKSTEEL = 100,
    VEHICLE_COLOR_METALLICDARKSTEEL = 101,
    VEHICLE_COLOR_METALLICSILVER = 102,
    VEHICLE_COLOR_METALLICBLUESTEEL = 103,
    VEHICLE_COLOR_METALLICAQUA = 104,
    VEHICLE_COLOR_METALLICPALEBLUE = 105,
    VEHICLE_COLOR_METALLICBLUE = 106,
    VEHICLE_COLOR_METALLICSEAFOAMBLUE = 107,
    VEHICLE_COLOR_METALLICLIGHTBLUE = 108,
    VEHICLE_COLOR_METALLICMIDNIGHTBLUE = 109,
    VEHICLE_COLOR_METALLICNAVYBLUE = 110,
    VEHICLE_COLOR_METALLICROYALBLUE = 111,
    VEHICLE_COLOR_METALLICLIGHTBLUE2 = 112,
    // add more special colors here

    VEHICLE_MAX_COLOR = 255
};