#pragma once

enum class eVehicleState 
{
    VEHICLE_IDLE,
    VEHICLE_ACCELERATING,
    VEHICLE_BRAKING,
    VEHICLE_TURNING_LEFT,
    VEHICLE_TURNING_RIGHT,
    VEHICLE_REVERSING,
    VEHICLE_CRASHED,
    VEHICLE_ON_FIRE,
    VEHICLE_EXPLODED
};