#pragma once

enum class eVehicleStatus 
{
    VEHICLE_STATUS_NORMAL,
    VEHICLE_STATUS_DAMAGED,
    VEHICLE_STATUS_DESTROYED,
    VEHICLE_STATUS_STOLEN,
    VEHICLE_STATUS_IMPOUNDED,
    VEHICLE_STATUS_ON_FIRE,
    VEHICLE_STATUS_EXPLODED,
    VEHICLE_STATUS_SUBMERGED,
    VEHICLE_STATUS_FLAT_TIRE,
    VEHICLE_STATUS_OUT_OF_FUEL
};