#pragma once

enum class eVehicleLights
{
    VEHICLE_LIGHTS_HEADLIGHTS = 1 << 0,
    VEHICLE_LIGHTS_TAiLLIGHTS = 1 << 1,
    VEHICLE_LIGHTS_BRAKE_LIGHTS = 1 << 2,
    VEHICLE_LIGHTS_LEFT_INDICATOR = 1 << 3,
    VEHICLE_LIGHTS_RIGHT_INDICATOR = 1 << 4,
    VEHICLE_LIGHTS_REVERSE_LIGHTS = 1 << 5,
    VEHICLE_LIGHTS_INTERIOR_LIGHTS = 1 << 6,
    VEHICLE_LIGHTS_HAZARD_LIGHTS = 1 << 7,
    VEHICLE_LIGHTS_FOG_LIGHTS = 1 << 8
};