#pragma once

enum class eVehicleStyleTraffic 
{
    VEHICLE_STYLE_CAR,
    VEHICLE_STYLE_VAN,
    VEHICLE_STYLE_TRUCK,
    VEHICLE_STYLE_MOTORCYCLE,
    VEHICLE_STYLE_BICYCLE,
    VEHICLE_STYLE_EMERGENCY,
    VEHICLE_STYLE_PUBLIC,
    VEHICLE_STYLE_SERVICE,
    VEHICLE_STYLE_OFFROAD,
    VEHICLE_STYLE_INDUSTRIAL,
    VEHICLE_STYLE_SPORTS,
    VEHICLE_STYLE_SUV,
    VEHICLE_STYLE_BOAT,
    VEHICLE_STYLE_HELI,
    VEHICLE_STYLE_PLANE
};