#pragma once

enum VehicleWindows
{
    WINDOW_FRONT_LEFT = 0,
    WINDOW_FRONT_RIGHT,
    WINDOW_REAR_LEFT,
    WINDOW_REAR_RIGHT,
    WINDOW_EXTRA_1,
    WINDOW_EXTRA_2,
    WINDOW_EXTRA_3,
    WINDOW_EXTRA_4,
    WINDOW_EXTRA_5,
    WINDOW_EXTRA_6,
    WINDOW_EXTRA_7,
    WINDOW_EXTRA_8,
    WINDOW_EXTRA_9,
    WINDOW_EXTRA_10
};